# Space Mouse Configuration for TeleopTwistStampedJoy
admittance_control:
  ros__parameters:
    # Publishing rate (Hz)
    publish_rate: 10.0
    
    # Scaling factors
   # force_scale: 1.0      # Max linear velocity (m/s)
    #torque_scale: 1.0     # Max angular velocity (rad/s)
    sphere_mass: 2.5 # mass of the object in kg for force control (kg)
    # inertia_x: 10.0
    # inertia_y: 10.0
    # inertia_z: 10.0
    # linear_drag_x: 100.0
    # linear_drag_y: 100.0
    # linear_drag_z: 100.0
    # rotational_drag_x: 100.0
    # rotational_drag_y: 100.0
    # rotational_drag_z: 100.0
    sphere_radius: 0.65  # Radius of the virtual sphere for admittance control (meters)
    fluid_viscosity: 1.0  # Viscosity coefficient for damping (PaÂ·s)

    
    # Frame ID for the twist messages
    frame_id: "eoat_camera_link"
    
    # Topic names
    wrench_topic: "/teleop/wrench_cmds"
    wrench_teleop_topic: "/teleop/wrench_cmds"
    wrench_orientation_topic: "/orientation_controller/wrench_cmds"
    twist_topic: "/servo_node/delta_twist_cmds"  # Updated topic for inspection cell
