orientation_controller:
  ros__parameters:
    depth_topic: /camera/d405_camera/depth/image_rect_raw/compressedDepth
    camera_info_topic: /camera/d405_camera/depth/camera_info #intrinsics info
    bounding_box_topic: /viewpoint_generation/bounding_box_marker #bounding box topic
    #depth map filtering range
    dmap_filter_min: 0.07
    dmap_filter_max: 0.50

    viz_enable: true
    publish_pointcloud: true
    pcd_downsampling_stride: 4
    #frame_ids 
    target_frame: object_frame #frame of the target object
    main_camera_frame: eoat_camera_link #frame of the eoat camera
    #cropped parameters in eoat camera frame
    crop_radius: 0.025
    crop_z_min: 0.05
    crop_z_max: 0.40
    
    standoff_m: 0.10 # standoff_value for fixed standoff mode
    standoff_mode: euclidean
    ema_enable: True
    ema_tau: 0.5

    normal_estimation_method: RANSAC #options: PCA, RANSAC
    visualize_normal_estimation: False

    no_target_timeout: 0.25
    publish_zero_when_lost: True
    orientation_control_enabled: False
    save_data: False
    object: ''
    data_path: '/data/OrientationControlData'
    sphere_mass: 2.5 # mass of the object in kg for force control (kg)
    sphere_radius: 0.65  # Radius of the virtual sphere for admittance control (meters)
    fluid_viscosity: 1.0  # Viscosity coefficient for damping (PaÂ·s)

    d_min: 0.15 # Minimum focal distance (meters)
    d_max: 0.30 # Maximum focal distance (meters)
    v_max: 0.40 # Maximum linear velocity (meters/second)
    theta_max_deg: 90.0 # Maximum angular displacement (degrees)

    controller_type: PID # Options: PID, PD

    Kp: 31.0
    Ki: 37.7
    Kd: 6.2
